### ISSUE TITLE
Upgrade to SwiCago/HeatPump version 1.0.0

### ISSUE THREAD

**Issue by geoffdavis** [geoffdavis/esphome-mitsubishiheatpump#70]
It looks like the SwiCago/HeatPump library has been updated a bit, and is now at a 1.0.0 release. We should support that version. There are API changes, so some work will need to be done to this library.

**Comment by grischard** [comment]
It looks like https://github.com/geoffdavis/esphome-mitsubishiheatpump/blob/e90072132cf0661d3fef0a4d24c9a9fe184e094d/components/mitsubishi_heatpump/climate.py#L93 installs [ed3b700dd4b110253368cc9f6960516d228e33d8](https://github.com/SwiCago/HeatPump/commit/ed3b700dd4b110253368cc9f6960516d228e33d8) from March, and https://github.com/SwiCago/HeatPump/pull/182 has been the only code change since, and that doesn't change the API? I'll try it out when I get around to it.
